apiVersion: v1
kind: Deployment
metadata:
  name: Consumer-deployment
  labels:
    app: consumer
spec:
  selector:
    matchLabels:
      app: consumer
    replicas: 1
    template:
      metadata:
        labels:
          app: consumer
      spec:
        container:
          - name: Consumer
            image: icsbariboa/consumer
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
---
apiVersion: v1
kind: service
metadata:
  name: consumer-service
  labels:
    app: consumer
spec:
  selector:
    name: consumer
  type: NodePort
  ports:
    - name: blank
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  containers:
    - name: consumer
      image: icsbariboa/consumer
      command: [ "/bin/sh" ]
      args:
        - -c
        - >-
          python consumer.py
          -p 5672
          -s rabbitmq