apiVersion: apps/v1
kind: Deployment
metadata:
  name: Producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: icsbariboa/producer
        resources:
        requests:
          cpu: 100m
          memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: producer
spec:
  selector:
    name: producer
  type: NodePort
  ports:
    - name: blank
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: producer
  labels:
    app: producer
spec:
  containers:
    - name: producer
      image: icsbariboa/producer
      command: ["/bin/sh"]
      args:
        - -c
        - >-
          python producer.py
          -p 5672
          -s rabbitmq
          -m "Hello"
          -r 30