apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  template:
    metadata:
      annotations:
      labels:
    spec:
      imagePullSecrets:
      serviceAccountName:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port }}
            - name: RABBITMQ_EXCHANGE
              value: {{ .Values.rabbitmq.exchange}}
            - name: MESSAGE_COUNT
              value: {{ .Values.messageCount }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              for ((i=1; i <= {{ .Values.messageCount }}; i++)); do
                if [ -n "{{ .Values.customMessage }}" ]; then
                  echo "{{ .Values.customMessage }}" | amqp-publish -u amqp://{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }} -e {{ .Values.rabbitmq.exchange }} -r custom
                else
                  echo "Hello, this is a default message!" | amqp-publish -u amqp://{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }} -e {{ .Values.rabbitmq.exchange }} -r default
                fi
              done
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
      affinity:
      tolerations:
