apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: producer
  labels:
  annotations:
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      secretName: {{ .secretName }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: producer
                port:
                  number: {{ $svcPort }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}